In [20]:
import matplotlib.pyplot as plt
%matplotlib inline
import numpy as np
import pandas as pd
import warnings
from sklearn import datasets, linear_model

import sklearn
from sklearn.linear_model import LogisticRegressionCV,LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model.coordinate_descent import ConvergenceWarning
import matplotlib as mpl

In [21]:
data = pd.read_csv('iBeacon_RSSI_Labeled.csv')

In [22]:
data = data.drop('date', 1)
#data.head()

,location,b3001,b3002,b3003,b3004,b3005,b3006,b3007,b3008,b3009,b3010,b3011,b3012,b3013
0,O02,-200,-200,-200,-200,-200,-78,-200,-200,-200,-200,-200,-200,-200
1,P01,-200,-200,-200,-200,-200,-78,-200,-200,-200,-200,-200,-200,-200
2,P01,-200,-200,-200,-200,-200,-77,-200,-200,-200,-200,-200,-200,-200
3,P01,-200,-200,-200,-200,-200,-77,-200,-200,-200,-200,-200,-200,-200
4,P01,-200,-200,-200,-200,-200,-77,-200,-200,-200,-200,-200,-200,-200

In [23]:
X = data[['b3001','b3002','b3003','b3004','b3005','b3006','b3007','b3008','b3009','b3010','b3011','b3012','b3013']]
X.shape

(1420, 13)

In [24]:
y = data[['location']]
#y.head()
#y_train.shape

  location
0      O02
1      P01
2      P01
3      P01
4      P01

In [25]:
from sklearn.cross_validation import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1)

In [26]:
print(X_train.shape)
print(y_train.shape)
print(X_test.shape)
print(y_test.shape)

(1065, 13)
(1065, 1)
(355, 13)
(355, 1)

In [27]:
#X_train.head()

,b3001,b3002,b3003,b3004,b3005,b3006,b3007,b3008,b3009,b3010,b3011,b3012,b3013
602,-200,-200,-200,-200,-200,-200,-200,-200,-78,-72,-200,-200,-200
1165,-200,-200,-77,-200,-200,-200,-200,-200,-200,-200,-200,-200,-200
62,-200,-77,-200,-200,-200,-200,-200,-200,-200,-200,-200,-200,-200
1199,-200,-200,-200,-78,-200,-200,-200,-200,-200,-200,-200,-200,-200
315,-200,-200,-200,-200,-200,-67,-200,-200,-200,-200,-200,-200,-200

In [28]:
#1、svm
from sklearn import svm
clf = svm.SVC(gamma=0.001)
clf.fit(X_train, y_train)

/anaconda3/lib/python3.6/site-packages/sklearn/utils/validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma=0.001, kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [29]:
clf.predict(X_test)

array(['J04', 'S01', 'L06', 'J07', 'I01', 'D15', 'M06', 'F08', 'S05',
       'S01', 'N06', 'J04', 'J04', 'N06', 'W15', 'N06', 'R04', 'R04',
       'S01', 'K04', 'J04', 'N05', 'S01', 'S01', 'O05', 'S01', 'J04',
       'K04', 'N03', 'O06', 'P15', 'J04', 'I01', 'S05', 'J04', 'W15',
       'O05', 'I01', 'S01', 'D13', 'M01', 'J04', 'J04', 'J04', 'D13',
       'S01', 'K04', 'N06', 'I01', 'L06', 'O06', 'J07', 'J04', 'N05',
       'I01', 'I01', 'N03', 'M03', 'I06', 'S05', 'M01', 'D13', 'S05',
       'N05', 'S05', 'J04', 'R04', 'N03', 'J04', 'S01', 'J04', 'R15',
       'J06', 'I07', 'J04', 'W15', 'M01', 'K04', 'L06', 'S01', 'S01',
       'I08', 'L06', 'D15', 'S01', 'O06', 'I10', 'R04', 'O06', 'N03',
       'K04', 'I01', 'S06', 'O05', 'M01', 'O06', 'J06', 'I08', 'N05',
       'P15', 'K04', 'S01', 'J04', 'M06', 'M03', 'I08', 'K07', 'S01',
       'S01', 'S01', 'J05', 'K05', 'S05', 'J04', 'L06', 'J06', 'S01',
       'S01', 'J04', 'M01', 'I10', 'S01', 'S01', 'S06', 'L15', 'N06',
       'L15', 'S01', 'D15', 'M01', 'D15', 'S05', 'M06', 'S01', 'R15',
       'S01', 'S01', 'K07', 'O06', 'J04', 'I01', 'S05', 'N03', 'N04',
       'K04', 'I10', 'M06', 'R04', 'S01', 'R15', 'J07', 'I06', 'N15',
       'I10', 'W15', 'J06', 'I08', 'J04', 'W15', 'I01', 'K07', 'J04',
       'S01', 'S06', 'N03', 'I01', 'O06', 'K04', 'K04', 'M03', 'S01',
       'K04', 'O05', 'W15', 'N03', 'J04', 'S06', 'N03', 'J06', 'D15',
       'L06', 'J04', 'M01', 'S01', 'I06', 'S01', 'J04', 'J04', 'S06',
       'S01', 'J04', 'I01', 'S05', 'J06', 'M03', 'K04', 'J04', 'J06',
       'S01', 'S01', 'I06', 'M01', 'N05', 'Q04', 'S01', 'M01', 'I01',
       'K04', 'S01', 'S01', 'M06', 'R04', 'I06', 'W15', 'K04', 'O06',
       'N05', 'O05', 'K04', 'J04', 'I08', 'S05', 'S05', 'J04', 'S05',
       'S05', 'K04', 'J06', 'S05', 'W15', 'S01', 'S06', 'S01', 'J07',
       'I07', 'I15', 'S01', 'S01', 'S01', 'N03', 'I08', 'M01', 'I06',
       'N03', 'L06', 'R04', 'I07', 'J07', 'J04', 'L06', 'L06', 'N05',
       'S01', 'S01', 'W15', 'S01', 'O06', 'J04', 'M01', 'J04', 'I08',
       'S01', 'L06', 'I01', 'S01', 'K05', 'O06', 'R04', 'J06', 'I01',
       'S01', 'J04', 'R04', 'J04', 'K03', 'O06', 'S01', 'J06', 'S01',
       'K04', 'K05', 'J04', 'S05', 'I08', 'J06', 'M01', 'J04', 'S06',
       'M06', 'D15', 'I01', 'I08', 'K04', 'W15', 'R04', 'O05', 'W15',
       'I01', 'S06', 'S01', 'D13', 'S05', 'O05', 'L06', 'M03', 'M01',
       'N04', 'M03', 'S01', 'S01', 'D13', 'S01', 'M06', 'D13', 'K04',
       'N06', 'O06', 'M03', 'S01', 'L06', 'S01', 'Q04', 'L06', 'L15',
       'N03', 'J04', 'I01', 'J06', 'K05', 'O06', 'R04', 'J04', 'J06',
       'S01', 'W15', 'J04', 'J04', 'S01', 'N05', 'M01', 'R04', 'S01',
       'O05', 'J07', 'K04', 'K04', 'K04', 'Q04', 'L06', 'J06', 'S01',
       'J04', 'S01', 'S06', 'I08'], dtype=object)

In [30]:
clf.score(X_test, y_test)

0.2028169014084507

In [31]:
clf.score(X_train, y_train)

0.29107981220657275

In [11]:
#2、决策树
from sklearn import tree
clf = tree.DecisionTreeClassifier()
clf = clf.fit(X_train, y_train)
clf.predict(X_test)

array(['J02', 'S01', 'J07', 'J07', 'J02', 'D15', 'J08', 'I04', 'Q05',
       'U04', 'O06', 'I04', 'J03', 'N01', 'V15', 'M06', 'S03', 'Q04',
       'S01', 'K04', 'I04', 'M02', 'O05', 'Q05', 'O05', 'O05', 'J03',
       'J02', 'M01', 'L02', 'P15', 'J02', 'I01', 'R05', 'I02', 'W15',
       'P05', 'K03', 'O05', 'D13', 'L04', 'I04', 'J01', 'I01', 'D13',
       'S01', 'K04', 'M06', 'J02', 'J07', 'L02', 'L05', 'I02', 'N05',
       'J01', 'I05', 'N02', 'N03', 'I06', 'S05', 'L04', 'D13', 'S05',
       'N05', 'S05', 'I02', 'Q01', 'N02', 'J03', 'U04', 'J03', 'R15',
       'J06', 'I10', 'K04', 'S15', 'K03', 'J02', 'J08', 'S01', 'R03',
       'I08', 'I03', 'D15', 'S01', 'L02', 'I08', 'S03', 'K06', 'L01',
       'J02', 'I01', 'S08', 'P05', 'M01', 'K06', 'M05', 'J02', 'L05',
       'P15', 'K04', 'P03', 'I04', 'K08', 'N03', 'I09', 'I10', 'O05',
       'P03', 'P03', 'J05', 'L04', 'S05', 'K04', 'L06', 'J06', 'S01',
       'P03', 'K04', 'L01', 'I10', 'R03', 'T05', 'R03', 'L15', 'N06',
       'L15', 'R03', 'D15', 'P01', 'D14', 'S05', 'K08', 'R03', 'R15',
       'S01', 'S01', 'I10', 'K06', 'J01', 'I01', 'S04', 'S03', 'O04',
       'Q04', 'I10', 'K06', 'S04', 'S01', 'T15', 'J07', 'I07', 'N15',
       'I10', 'W15', 'K06', 'I07', 'I01', 'T15', 'I05', 'K07', 'I01',
       'O05', 'S07', 'N03', 'I05', 'K06', 'K04', 'P04', 'N03', 'Q05',
       'J02', 'P05', 'W15', 'N02', 'J03', 'R05', 'N01', 'I06', 'D15',
       'K07', 'I01', 'M04', 'S01', 'I06', 'S01', 'K04', 'I04', 'S07',
       'O05', 'I01', 'J02', 'Q05', 'I06', 'M03', 'J03', 'I02', 'J06',
       'S01', 'S01', 'I06', 'P01', 'M02', 'Q05', 'O05', 'M01', 'J02',
       'J02', 'R03', 'T05', 'K08', 'P03', 'I06', 'W15', 'K05', 'J01',
       'M02', 'P05', 'K03', 'I02', 'I07', 'S05', 'S04', 'J02', 'Q05',
       'Q05', 'K04', 'I06', 'S05', 'U15', 'O05', 'S07', 'S01', 'I07',
       'I09', 'G15', 'P03', 'O05', 'S01', 'M02', 'N05', 'L01', 'I06',
       'M06', 'J06', 'S04', 'I07', 'L05', 'K04', 'J07', 'K08', 'M06',
       'O05', 'S01', 'V15', 'S01', 'J01', 'J04', 'M04', 'I02', 'J06',
       'R03', 'L06', 'J02', 'O05', 'I02', 'K06', 'Q01', 'J05', 'I05',
       'O05', 'J04', 'O03', 'I02', 'J08', 'J01', 'P03', 'I06', 'S01',
       'K04', 'J01', 'K04', 'S04', 'I07', 'I05', 'K03', 'J02', 'R05',
       'J08', 'D15', 'J02', 'N15', 'I03', 'V15', 'P03', 'P05', 'V15',
       'J02', 'S08', 'S01', 'D13', 'S04', 'O06', 'L06', 'N03', 'L01',
       'O04', 'N02', 'P03', 'P03', 'D13', 'R03', 'K06', 'D13', 'P04',
       'N06', 'P01', 'N02', 'S01', 'J07', 'R03', 'M04', 'K07', 'N15',
       'M02', 'K04', 'J01', 'J04', 'I04', 'P01', 'P03', 'J01', 'I05',
       'O05', 'V15', 'I01', 'I02', 'S01', 'N05', 'M01', 'Q01', 'P03',
       'O05', 'J07', 'N01', 'I03', 'I03', 'Q04', 'K07', 'I03', 'Q05',
       'J01', 'T05', 'R03', 'I08'], dtype=object)

In [ ]:
clf.score()

In [ ]:
clf.score(X_test, y_test)

In [ ]:
clf.score(X_train, y_train)

In [36]:
from sklearn import preprocessing  
le =preprocessing.LabelEncoder()  
le.fit(y_train)  
#print('标签个数:%s'% le.classes_)  
y_train=le.transform(y_train)
#print('标准化标签值反转:%s' % le.inverse_transform([2, 2, 1]))  

#标签个数:['amsterdam' 'paris' 'tokyo']  
#标签值标准化:[2 2 1]  
#标准化标签值反转:['tokyo' 'tokyo' 'paris']
y_train

array([16, 73, 37, ..., 20, 54, 39])

In [46]:
#3、随机森林
from sklearn import tree
clf = tree.DecisionTreeRegressor()
clf = clf.fit(X_train, y_train)
clf.predict(X_test)

array([ 18.7       ,  84.6875    ,  24.2       ,  23.        ,
        16.85714286,   2.        ,  32.        ,   4.        ,
        82.18181818,  86.9       ,  53.4       ,  14.16666667,
        16.83333333,  56.        , 103.        ,  55.33333333,
        85.        ,  73.        ,  84.6875    ,  18.44444444,
        14.16666667,  54.75      ,  78.625     ,  84.72727273,
        61.        ,  86.29411765,  18.44444444,   8.        ,
        35.        ,  56.14285714,  43.        ,  18.7       ,
        20.        ,  80.        ,  21.3       , 104.        ,
        67.        ,  23.55555556,  86.29411765,   0.        ,
        51.        ,  14.16666667,  22.        ,  20.9       ,
         0.        ,  81.86363636,  30.        ,  55.33333333,
        16.85714286,  24.2       ,  56.14285714,  39.        ,
        24.83333333,  46.9       ,  33.16666667,  24.        ,
        51.        ,  46.        ,  11.        ,  87.4       ,
        51.        ,   0.        ,  87.4       ,  46.9       ,
        87.4       ,  24.83333333,  72.        ,  51.        ,
        18.44444444,  86.9       ,  16.83333333,  82.        ,
        24.83333333,  15.        ,  22.93333333,  91.        ,
        40.        ,  18.        ,  32.33333333,  81.86363636,
        79.48148148,  13.        ,  24.8       ,   2.        ,
        81.86363636,  56.14285714,  13.        ,  72.        ,
        39.4       ,  36.        ,  18.        ,  18.875     ,
        82.33333333,  67.        ,  45.        ,  39.4       ,
        32.        ,  85.        ,  41.        ,  69.        ,
        30.        ,  77.64285714,  14.16666667,  37.        ,
        44.        ,  14.        ,  33.        ,  78.625     ,
        77.64285714,  77.64285714,  21.        ,  38.        ,
        87.4       ,  22.93333333,  33.6       ,  14.        ,
        81.86363636,  77.64285714,  22.93333333,  50.5       ,
        15.        ,  79.48148148,  83.625     ,  82.33333333,
        43.        ,  55.        ,  43.        ,  79.48148148,
         2.        ,  54.75      ,   1.        ,  87.4       ,
        34.        ,  79.48148148,  82.        ,  78.2       ,
        78.2       ,  33.        ,  39.4       ,  22.        ,
        20.        ,  86.        ,  67.        ,  60.        ,
        73.        ,  15.        ,  32.        ,  86.        ,
        81.86363636,  96.        ,  23.        ,  12.        ,
        56.        ,  15.        , 104.        ,  32.        ,
        87.66666667,  16.66666667,  96.        ,  24.        ,
        33.        ,  14.22222222,  78.625     ,  89.5       ,
        67.        ,  24.        ,  39.4       ,  30.        ,
        66.        ,  52.        ,  84.72727273,  18.        ,
        61.        , 104.        ,  51.        ,  18.44444444,
        87.66666667,  56.        ,  11.        ,   2.        ,
        38.125     ,  14.22222222,  56.5       ,  81.86363636,
        11.        ,  78.2       ,  22.93333333,  14.16666667,
        89.5       ,  78.625     ,  16.66666667,  16.85714286,
        82.18181818,  11.        ,  46.        ,  30.        ,
        23.        ,  32.        ,  84.6875    ,  81.86363636,
        11.        ,  54.75      ,  54.75      ,  74.        ,
        86.29411765,  45.        ,  16.85714286,   8.        ,
        79.48148148,  83.625     ,  37.        ,  65.        ,
        11.        , 104.        ,  37.66666667,  39.28571429,
        56.33333333,  67.        ,  18.        ,  24.83333333,
        87.66666667,  86.33333333,  86.        ,  18.7       ,
        87.        ,  87.        ,  30.        ,  11.        ,
        87.4       , 102.        ,  86.29411765,  89.5       ,
        81.86363636,  20.        ,  14.        ,  10.5       ,
        77.64285714,  86.29411765,  81.86363636,  48.5       ,
        15.        ,  50.5       ,  11.        ,  51.        ,
        28.        ,  86.        ,  12.        ,  39.        ,
        22.33333333,  24.2       ,  37.        ,  49.        ,
        86.29411765,  78.2       , 103.        ,  84.6875    ,
        39.28571429,  21.66666667,  60.        ,  23.        ,
        23.55555556,  79.48148148,  47.5       ,  16.85714286,
        78.625     ,   7.        ,  39.4       ,  70.        ,
        21.        ,  24.        ,  78.625     ,  21.66666667,
        70.        ,  21.3       ,  24.        ,  39.28571429,
        77.64285714,  11.        ,  83.        ,  30.        ,
        31.        ,  22.93333333,  86.        ,  12.        ,
        48.        ,  40.        ,  18.7       ,  87.66666667,
        32.        ,   2.        ,  16.85714286, 100.33333333,
         8.        , 103.        ,  65.        ,  67.        ,
       103.        ,  16.85714286,  80.        ,  81.86363636,
         0.        ,  86.        ,  67.        ,  40.        ,
        52.        ,  50.5       ,  60.        ,  51.        ,
        77.64285714,  77.64285714,   1.5       ,  79.48148148,
        32.        ,   0.        ,  66.        ,  55.        ,
        47.05555556,  55.5       ,  78.2       ,  24.2       ,
        79.48148148,  73.        ,  38.125     ,  56.        ,
        48.5       ,  22.93333333,  33.16666667,  21.66666667,
         9.        ,  47.05555556,  65.        ,  22.        ,
        10.        ,  86.29411765, 103.        ,  20.9       ,
        24.83333333,  84.6875    ,  46.9       ,  45.        ,
        70.        ,  77.64285714,  61.        ,  23.        ,
        50.        ,  32.5       ,   8.        ,  73.        ,
        38.125     ,   8.        ,  84.72727273,  22.        ,
        83.625     ,  82.33333333,  33.        ])

In [45]:
X_test=le.transform(X_test)
clf.score(X_test, y_test)

ValueError: bad input shape (355, 13)

In [39]:
y_test

     location
169       M04
37        S02
512       I07
912       J07
341       K06
383       D15
435       J07
1086      I04
1023      Q05
1040      O05
223       L05
48        J03
194       J04
236       N05
863       W15
311       O06
80        O03
1163      Q04
259       Q05
830       I02
1117      L04
487       M02
101       R03
685       S08
1047      O05
1227      Q03
432       J06
572       K04
481       M01
301       Q06
...       ...
767       J04
709       L02
1078      J05
921       I04
303       P06
1233      P03
216       K05
819       I04
1318      S01
631       V15
202       I04
916       J02
989       S06
310       O06
1268      K03
653       S04
8         R01
241       O05
368       J07
494       N01
757       J02
735       K04
1062      L05
1059      M05
821       I03
275       R05
1083      I05
643       S02
994       S06
804       I08

[355 rows x 1 columns]

In [19]:
Y_test

array([ 18.7       ,  84.6875    ,  24.2       ,  23.        ,
        16.85714286,   2.        ,  32.        ,   4.        ,
        82.18181818,  86.9       ,  53.4       ,  14.16666667,
        16.83333333,  56.        , 103.        ,  55.33333333,
        85.        ,  73.        ,  84.6875    ,  18.44444444,
        14.16666667,  54.75      ,  78.625     ,  84.72727273,
        61.        ,  86.29411765,  18.44444444,   8.        ,
        35.        ,  56.14285714,  43.        ,  18.7       ,
        20.        ,  80.        ,  21.3       , 104.        ,
        67.        ,  23.55555556,  86.29411765,   0.        ,
        51.        ,  14.16666667,  22.        ,  20.9       ,
         0.        ,  81.86363636,  30.        ,  55.33333333,
        16.85714286,  24.2       ,  56.14285714,  39.        ,
        24.83333333,  46.9       ,  33.16666667,  24.        ,
        51.        ,  46.        ,  11.        ,  87.4       ,
        51.        ,   0.        ,  87.4       ,  46.9       ,
        87.4       ,  24.83333333,  72.        ,  51.        ,
        18.44444444,  86.9       ,  16.83333333,  82.        ,
        24.83333333,  15.        ,  22.93333333,  91.        ,
        40.        ,  18.        ,  32.33333333,  81.86363636,
        79.48148148,  13.        ,  24.8       ,   2.        ,
        81.86363636,  56.14285714,  13.        ,  72.        ,
        39.4       ,  36.        ,  18.        ,  18.875     ,
        82.33333333,  67.        ,  45.        ,  39.4       ,
        32.        ,  85.        ,  41.        ,  69.        ,
        29.        ,  77.64285714,  14.16666667,  37.        ,
        44.        ,  14.        ,  33.        ,  78.625     ,
        77.64285714,  77.64285714,  21.        ,  38.        ,
        87.4       ,  22.93333333,  33.6       ,  24.        ,
        81.86363636,  77.64285714,  22.93333333,  50.5       ,
        15.        ,  79.48148148,  83.625     ,  82.33333333,
        43.        ,  55.        ,  43.        ,  79.48148148,
         2.        ,  54.75      ,   1.        ,  87.4       ,
        34.        ,  79.48148148,  82.        ,  78.2       ,
        78.2       ,  33.        ,  39.4       ,  22.        ,
        20.        ,  86.        ,  67.        ,  60.        ,
        73.        ,  15.        ,  32.        ,  86.        ,
        81.86363636,  96.        ,  23.        ,  12.        ,
        56.        ,  15.        , 104.        ,  32.        ,
        87.66666667,  16.66666667,  96.        ,  24.        ,
        33.        ,  14.22222222,  78.625     ,  89.5       ,
        67.        ,  24.        ,  39.4       ,  30.        ,
        66.        ,  52.        ,  84.72727273,  18.        ,
        61.        , 104.        ,  51.        ,  18.44444444,
        87.66666667,  56.        ,  11.        ,   2.        ,
        38.125     ,  14.22222222,  56.5       ,  81.86363636,
        11.        ,  78.2       ,  22.93333333,  14.16666667,
        89.5       ,  78.625     ,  16.66666667,  16.85714286,
        82.18181818,  11.        ,  46.        ,  29.        ,
        23.        ,  32.        ,  84.6875    ,  81.86363636,
        10.        ,  54.75      ,  54.75      ,  74.        ,
        86.29411765,  45.        ,  16.85714286,   8.        ,
        79.48148148,  83.625     ,  37.        ,  65.        ,
        11.        , 104.        ,  37.66666667,  39.28571429,
        56.33333333,  67.        ,  18.        ,  24.83333333,
        87.66666667,  86.33333333,  86.        ,  18.7       ,
        87.        ,  87.        ,  30.        ,  11.        ,
        87.4       , 102.        ,  86.29411765,  89.5       ,
        81.86363636,  20.        ,  14.        ,  10.5       ,
        77.64285714,  86.29411765,  81.86363636,  48.5       ,
        15.        ,  50.5       ,  11.        ,  51.        ,
        28.        ,  86.        ,  12.        ,  39.        ,
        22.33333333,  24.2       ,  37.        ,  49.        ,
        86.29411765,  78.2       , 103.        ,  84.6875    ,
        39.28571429,  21.66666667,  60.        ,  23.        ,
        23.55555556,  79.48148148,  47.5       ,  16.85714286,
        78.625     ,   7.        ,  39.4       ,  70.        ,
        21.        ,  24.        ,  78.625     ,  21.66666667,
        70.        ,  21.3       ,  24.        ,  39.28571429,
        77.64285714,  11.        ,  83.        ,  30.        ,
        31.        ,  22.93333333,  86.        ,  12.        ,
        48.        ,  40.        ,  18.7       ,  87.66666667,
        32.        ,   2.        ,  16.85714286, 100.33333333,
         8.        , 103.        ,  70.        ,  67.        ,
       103.        ,  16.85714286,  80.        ,  81.86363636,
         0.        ,  86.        ,  67.        ,  40.        ,
        52.        ,  50.5       ,  60.        ,  51.        ,
        77.64285714,  77.64285714,   1.5       ,  79.48148148,
        32.        ,   0.        ,  66.        ,  55.        ,
        47.05555556,  55.5       ,  78.2       ,  24.2       ,
        79.48148148,  73.        ,  38.125     ,  56.        ,
        48.5       ,  22.93333333,  33.16666667,  21.66666667,
         9.        ,  47.05555556,  65.        ,  22.        ,
        10.        ,  86.29411765, 103.        ,  20.9       ,
        24.83333333,  84.6875    ,  46.9       ,  45.        ,
        70.        ,  77.64285714,  61.        ,  23.        ,
        50.        ,  32.5       ,   8.        ,  73.        ,
        38.125     ,   8.        ,  84.72727273,  22.        ,
        83.625     ,  82.33333333,  33.        ])